### ISSUE TITLE
path for lspci can be /usr/bin as well

### ISSUE THREAD

**Issue by susheelvyas** [xxr3376/golspci#2]
https://github.com/xxr3376/golspci/blob/7ee67e81749c891a312a0625ee5bff1c3a3d657c/lspci/lspci.go#L87

lspci aslo does resides on /usr/bin, can you please add it as well.

root@kvm-x86-64:/usr/sbin# which lspci
/usr/bin/lspci
root@kvm-x86-64

root@kvm-x86-64:/var/tmp# ./lspci
panic: Unable to find the 'lspci' binary

goroutine 1 [running]:
main.main()
/home/svyas/latest9/tierra-os/common/src/system/lspci.go:14 +0x9b
root@kvm-x86-64:/var/tmp#

**Comment by susheelvyas** [comment]
root@kvm-x86-64:/usr/sbin# which lspci
/usr/bin/lspci
root@kvm-x86-64

root@kvm-x86-64:/var/tmp# ./lspci
panic: Unable to find the 'lspci' binary

goroutine 1 [running]:
main.main()
/home/svyas/latest9/tierra-os/common/src/system/lspci.go:14 +0x9b
root@kvm-x86-64:/var/tmp#

**Comment by susheelvyas** [comment]
root@kvm-x86-64:/var/tmp# ./lspci
panic: Unable to find the 'lspci' binary

goroutine 1 [running]:
main.main()
        /home/svyas/latest9/tierra-os/common/src/system/lspci.go:14 +0x9b
root@kvm-x86-64:/var/tmp#
